import { Stripe } from "./stripe.server"

export const invoice: Stripe.Invoice = {
  id: "in_1LZcyCKhNIAUaK2Oq3K8YCm1",
  object: "invoice",
  account_country: "US",
  account_name: "Pocket Network, Inc.",
  account_tax_ids: null,
  amount_due: 0,
  amount_paid: 0,
  amount_remaining: 0,
  application: null,
  application_fee_amount: null,
  attempt_count: 0,
  attempted: true,
  auto_advance: false,
  automatic_tax: {
    enabled: false,
    status: null,
  },
  billing_reason: "subscription_create",
  charge: null,
  collection_method: "charge_automatically",
  created: 1661183720,
  currency: "usd",
  custom_fields: null,
  customer: "cus_MGMR6lph7wxZrw",
  customer_address: null,
  customer_email: "kevin.utoft@gmail.com",
  customer_name: null,
  customer_phone: null,
  customer_shipping: null,
  customer_tax_exempt: "none",
  customer_tax_ids: [],
  default_payment_method: null,
  default_source: null,
  default_tax_rates: [],
  description: null,
  discount: null,
  discounts: [],
  due_date: null,
  ending_balance: 0,
  footer: null,
  hosted_invoice_url:
    "https://invoice.stripe.com/i/acct_1LB3dGKhNIAUaK2O/test_YWNjdF8xTEIzZEdLaE5JQVVhSzJPLF9NSURQWklZYUNNUzE3ZXNoWmlsMmFjaHpJMVBvQzhpLDUxNzQ0MTE20200SewAiGHX?s=ap",
  invoice_pdf:
    "https://pay.stripe.com/invoice/acct_1LB3dGKhNIAUaK2O/test_YWNjdF8xTEIzZEdLaE5JQVVhSzJPLF9NSURQWklZYUNNUzE3ZXNoWmlsMmFjaHpJMVBvQzhpLDUxNzQ0MTE20200SewAiGHX/pdf?s=ap",
  last_finalization_error: null,
  lines: {
    object: "list",
    data: [
      {
        id: "il_1LZcyCKhNIAUaK2OI2BoGWZ5",
        object: "line_item",
        amount: 0,
        currency: "usd",
        description: "0 × Pokemon Relays (at $0.00 / month)",
        discount_amounts: [],
        discountable: true,
        discounts: [],
        livemode: false,
        metadata: {
          endpoint_id: "f3cbb43cc8a0c93b291d3627",
          endpoint_name: "Subscription 6",
        },
        period: {
          end: 1663861820,
          start: 1661183720,
        },
        plan: {
          id: "price_1LUzM7KhNIAUaK2O2JOUw5iU",
          object: "plan",
          active: true,
          aggregate_usage: "sum",
          amount: null,
          amount_decimal: null,
          billing_scheme: "tiered",
          created: 1660078131,
          currency: "usd",
          interval: "month",
          interval_count: 1,
          livemode: false,
          metadata: {},
          nickname: null,
          product: "prod_MDQC1oAKQ1geep",
          tiers_mode: "volume",
          transform_usage: null,
          trial_period_days: null,
          usage_type: "metered",
        },
        price: {
          id: "price_1LUzM7KhNIAUaK2O2JOUw5iU",
          object: "price",
          active: true,
          billing_scheme: "tiered",
          created: 1660078131,
          currency: "usd",
          custom_unit_amount: null,
          livemode: false,
          lookup_key: null,
          metadata: {},
          nickname: null,
          product: "prod_MDQC1oAKQ1geep",
          recurring: {
            aggregate_usage: "sum",
            interval: "month",
            interval_count: 1,
            trial_period_days: null,
            usage_type: "metered",
          },
          tax_behavior: "unspecified",
          tiers_mode: "volume",
          transform_quantity: null,
          type: "recurring",
          unit_amount: null,
          unit_amount_decimal: null,
        },
        proration: false,
        proration_details: {
          credited_items: null,
        },
        quantity: 0,
        subscription: "sub_1LZcyCKhNIAUaK2Oi91NbB2f",
        subscription_item: "si_MIDPmHAn3pRYAp",
        tax_amounts: [],
        tax_rates: [],
        type: "subscription",
      },
    ],
    has_more: false,
    url: "/v1/invoices/in_1LZcyCKhNIAUaK2Oq3K8YCm1/lines",
  },
  livemode: false,
  metadata: {},
  next_payment_attempt: null,
  number: "F295E67C-0005",
  on_behalf_of: null,
  paid: true,
  paid_out_of_band: false,
  payment_intent: null,
  payment_settings: {
    payment_method_options: null,
    payment_method_types: null,
  },
  period_end: 1661183720,
  period_start: 1661183720,
  post_payment_credit_notes_amount: 0,
  pre_payment_credit_notes_amount: 0,
  quote: null,
  receipt_number: null,
  rendering_options: null,
  starting_balance: 0,
  statement_descriptor: null,
  status: "paid",
  status_transitions: {
    finalized_at: 1661183720,
    marked_uncollectible_at: null,
    paid_at: 1661183720,
    voided_at: null,
  },
  subscription: "sub_1LZcyCKhNIAUaK2Oi91NbB2f",
  subtotal: 0,
  tax: null,
  test_clock: null,
  total: 0,
  total_discount_amounts: [],
  total_tax_amounts: [],
  transfer_data: null,
  webhooks_delivered_at: 1661183720,
}

export const subscription: Stripe.Subscription = {
  id: "sub_1LZcyCKhNIAUaK2Oi91NbB2f",
  object: "subscription",
  application: null,
  application_fee_percent: null,
  automatic_tax: {
    enabled: false,
  },
  billing_cycle_anchor: 1661183720,
  billing_thresholds: null,
  cancel_at: null,
  cancel_at_period_end: false,
  canceled_at: null,
  collection_method: "charge_automatically",
  created: 1661183720,
  current_period_end: 1663862120,
  current_period_start: 1661183720,
  customer: "cus_MGMR6lph7wxZrw",
  days_until_due: null,
  default_payment_method: "pm_1LXqAGKhNIAUaK2OezCKiR62",
  default_source: null,
  default_tax_rates: [],
  description: null,
  discount: null,
  ended_at: null,
  items: {
    object: "list",
    data: [
      {
        id: "si_MIDPmHAn3pRYAp",
        object: "subscription_item",
        billing_thresholds: null,
        created: 1661183720,
        metadata: {},
        plan: {
          id: "price_1LUzM7KhNIAUaK2O2JOUw5iU",
          object: "plan",
          active: true,
          aggregate_usage: "sum",
          amount: null,
          amount_decimal: null,
          billing_scheme: "tiered",
          created: 1660078131,
          currency: "usd",
          interval: "month",
          interval_count: 1,
          livemode: false,
          metadata: {},
          nickname: null,
          product: "prod_MDQC1oAKQ1geep",
          tiers_mode: "volume",
          transform_usage: null,
          trial_period_days: null,
          usage_type: "metered",
        },
        price: {
          id: "price_1LUzM7KhNIAUaK2O2JOUw5iU",
          object: "price",
          active: true,
          billing_scheme: "tiered",
          created: 1660078131,
          currency: "usd",
          custom_unit_amount: null,
          livemode: false,
          lookup_key: null,
          metadata: {},
          nickname: null,
          product: "prod_MDQC1oAKQ1geep",
          recurring: {
            aggregate_usage: "sum",
            interval: "month",
            interval_count: 1,
            trial_period_days: null,
            usage_type: "metered",
          },
          tax_behavior: "unspecified",
          tiers_mode: "volume",
          transform_quantity: null,
          type: "recurring",
          unit_amount: null,
          unit_amount_decimal: null,
        },
        subscription: "sub_1LZcyCKhNIAUaK2Oi91NbB2f",
        tax_rates: [],
      },
    ],
    has_more: false,
    url: "/v1/subscription_items?subscription=sub_1LZcyCKhNIAUaK2Oi91NbB2f",
  },
  latest_invoice: "in_1LZcyCKhNIAUaK2Oq3K8YCm1",
  livemode: false,
  metadata: {
    endpoint_id: "f3cbb43cc8a0c93b291d3627",
    endpoint_name: "Subscription 6",
  },
  next_pending_invoice_item_invoice: null,
  pause_collection: null,
  payment_settings: {
    payment_method_options: null,
    payment_method_types: null,
    save_default_payment_method: "off",
  },
  pending_invoice_item_interval: null,
  pending_setup_intent: null,
  pending_update: null,
  schedule: null,
  start_date: 1661183720,
  status: "active",
  test_clock: null,
  transfer_data: null,
  trial_end: null,
  trial_start: null,
}

export const useageRecord: Stripe.ApiList<Stripe.UsageRecordSummary> = {
  object: "list",
  data: [
    {
      id: "sis_1LZi4GKhNIAUaK2OfuO2rYZ0",
      object: "usage_record_summary",
      invoice: null,
      livemode: false,
      period: {
        end: null,
        start: null,
      },
      subscription_item: "si_MIDPmHAn3pRYAp",
      total_usage: 0,
    },
  ],
  has_more: false,
  url: "/v1/subscription_items/si_MIDPmHAn3pRYAp/usage_record_summaries",
}
