/* tslint:disable */
/* eslint-disable */
/**
 * Portal DWH Service API
 * Service that provides data from DWH to the Portal
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnalyticsRelaysTransactions
 */
export interface AnalyticsRelaysTransactions {
    /**
     * 
     * @type {Date}
     * @memberof AnalyticsRelaysTransactions
     */
    from?: Date;
    /**
     * 
     * @type {Date}
     * @memberof AnalyticsRelaysTransactions
     */
    to?: Date;
    /**
     * 
     * @type {string}
     * @memberof AnalyticsRelaysTransactions
     */
    accountId?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalyticsRelaysTransactions
     */
    portalApplicationId?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalyticsRelaysTransactions
     */
    chainId?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalyticsRelaysTransactions
     */
    chainMethod?: string;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsRelaysTransactions
     */
    errorRate?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsRelaysTransactions
     */
    cnt?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsRelaysTransactions
     */
    avgRoundtripTime?: number;
}

/**
 * Check if a given object implements the AnalyticsRelaysTransactions interface.
 */
export function instanceOfAnalyticsRelaysTransactions(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AnalyticsRelaysTransactionsFromJSON(json: any): AnalyticsRelaysTransactions {
    return AnalyticsRelaysTransactionsFromJSONTyped(json, false);
}

export function AnalyticsRelaysTransactionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsRelaysTransactions {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'from': !exists(json, 'from') ? undefined : (new Date(json['from'])),
        'to': !exists(json, 'to') ? undefined : (new Date(json['to'])),
        'accountId': !exists(json, 'account_id') ? undefined : json['account_id'],
        'portalApplicationId': !exists(json, 'portal_application_id') ? undefined : json['portal_application_id'],
        'chainId': !exists(json, 'chain_id') ? undefined : json['chain_id'],
        'chainMethod': !exists(json, 'chain_method') ? undefined : json['chain_method'],
        'errorRate': !exists(json, 'error_rate') ? undefined : json['error_rate'],
        'cnt': !exists(json, 'cnt') ? undefined : json['cnt'],
        'avgRoundtripTime': !exists(json, 'avg_roundtrip_time') ? undefined : json['avg_roundtrip_time'],
    };
}

export function AnalyticsRelaysTransactionsToJSON(value?: AnalyticsRelaysTransactions | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'from': value.from === undefined ? undefined : (value.from.toISOString().substring(0,10)),
        'to': value.to === undefined ? undefined : (value.to.toISOString().substring(0,10)),
        'account_id': value.accountId,
        'portal_application_id': value.portalApplicationId,
        'chain_id': value.chainId,
        'chain_method': value.chainMethod,
        'error_rate': value.errorRate,
        'cnt': value.cnt,
        'avg_roundtrip_time': value.avgRoundtripTime,
    };
}

