/* tslint:disable */
/* eslint-disable */
/**
 * Portal DWH Service API
 * Service that provides data from DWH to the Portal
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnalyticsRelaysAggregated
 */
export interface AnalyticsRelaysAggregated {
    /**
     * 
     * @type {Date}
     * @memberof AnalyticsRelaysAggregated
     */
    date?: Date;
    /**
     * 
     * @type {string}
     * @memberof AnalyticsRelaysAggregated
     */
    categoryValue?: string;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsRelaysAggregated
     */
    rateSuccess?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsRelaysAggregated
     */
    rateError?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsRelaysAggregated
     */
    countTotal?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsRelaysAggregated
     */
    avgLatency?: number;
}

/**
 * Check if a given object implements the AnalyticsRelaysAggregated interface.
 */
export function instanceOfAnalyticsRelaysAggregated(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AnalyticsRelaysAggregatedFromJSON(json: any): AnalyticsRelaysAggregated {
    return AnalyticsRelaysAggregatedFromJSONTyped(json, false);
}

export function AnalyticsRelaysAggregatedFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsRelaysAggregated {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'date': !exists(json, 'date') ? undefined : (new Date(json['date'])),
        'categoryValue': !exists(json, 'category_value') ? undefined : json['category_value'],
        'rateSuccess': !exists(json, 'rate_success') ? undefined : json['rate_success'],
        'rateError': !exists(json, 'rate_error') ? undefined : json['rate_error'],
        'countTotal': !exists(json, 'count_total') ? undefined : json['count_total'],
        'avgLatency': !exists(json, 'avg_latency') ? undefined : json['avg_latency'],
    };
}

export function AnalyticsRelaysAggregatedToJSON(value?: AnalyticsRelaysAggregated | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'date': value.date === undefined ? undefined : (value.date.toISOString().substring(0,10)),
        'category_value': value.categoryValue,
        'rate_success': value.rateSuccess,
        'rate_error': value.rateError,
        'count_total': value.countTotal,
        'avg_latency': value.avgLatency,
    };
}

