/* tslint:disable */
/* eslint-disable */
/**
 * Portal DWH Service API
 * Service that provides data from DWH to the Portal
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnalyticsRelaysTotal
 */
export interface AnalyticsRelaysTotal {
    /**
     * 
     * @type {Date}
     * @memberof AnalyticsRelaysTotal
     */
    from?: Date;
    /**
     * 
     * @type {Date}
     * @memberof AnalyticsRelaysTotal
     */
    to?: Date;
    /**
     * 
     * @type {string}
     * @memberof AnalyticsRelaysTotal
     */
    categoryValue?: string;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsRelaysTotal
     */
    rateSuccess?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsRelaysTotal
     */
    rateError?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsRelaysTotal
     */
    countTotal?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsRelaysTotal
     */
    avgLatency?: number;
}

/**
 * Check if a given object implements the AnalyticsRelaysTotal interface.
 */
export function instanceOfAnalyticsRelaysTotal(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AnalyticsRelaysTotalFromJSON(json: any): AnalyticsRelaysTotal {
    return AnalyticsRelaysTotalFromJSONTyped(json, false);
}

export function AnalyticsRelaysTotalFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsRelaysTotal {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'from': !exists(json, 'from') ? undefined : (new Date(json['from'])),
        'to': !exists(json, 'to') ? undefined : (new Date(json['to'])),
        'categoryValue': !exists(json, 'category_value') ? undefined : json['category_value'],
        'rateSuccess': !exists(json, 'rate_success') ? undefined : json['rate_success'],
        'rateError': !exists(json, 'rate_error') ? undefined : json['rate_error'],
        'countTotal': !exists(json, 'count_total') ? undefined : json['count_total'],
        'avgLatency': !exists(json, 'avg_latency') ? undefined : json['avg_latency'],
    };
}

export function AnalyticsRelaysTotalToJSON(value?: AnalyticsRelaysTotal | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'from': value.from === undefined ? undefined : (value.from.toISOString().substring(0,10)),
        'to': value.to === undefined ? undefined : (value.to.toISOString().substring(0,10)),
        'category_value': value.categoryValue,
        'rate_success': value.rateSuccess,
        'rate_error': value.rateError,
        'count_total': value.countTotal,
        'avg_latency': value.avgLatency,
    };
}

