/* tslint:disable */
/* eslint-disable */
/**
 * Portal DWH Service API
 * Service that provides data from DWH to the Portal
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
/**
 *
 * @export
 * @interface AnalyticsGrowth
 */
export interface AnalyticsGrowth {
  /**
   *
   * @type {Date}
   * @memberof AnalyticsGrowth
   */
  from?: Date
  /**
   *
   * @type {Date}
   * @memberof AnalyticsGrowth
   */
  to?: Date
  /**
   *
   * @type {number}
   * @memberof AnalyticsGrowth
   */
  cnt?: number
  /**
   *
   * @type {number}
   * @memberof AnalyticsGrowth
   */
  growthRate?: number
}

/**
 * Check if a given object implements the AnalyticsGrowth interface.
 */
export function instanceOfAnalyticsGrowth(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function AnalyticsGrowthFromJSON(json: any): AnalyticsGrowth {
  return AnalyticsGrowthFromJSONTyped(json, false)
}

export function AnalyticsGrowthFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AnalyticsGrowth {
  if (json === undefined || json === null) {
    return json
  }
  return {
    from: !exists(json, "from") ? undefined : new Date(json["from"]),
    to: !exists(json, "to") ? undefined : new Date(json["to"]),
    cnt: !exists(json, "cnt") ? undefined : json["cnt"],
    growthRate: !exists(json, "growth_rate") ? undefined : json["growth_rate"],
  }
}

export function AnalyticsGrowthToJSON(value?: AnalyticsGrowth | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    from:
      value.from === undefined ? undefined : value.from.toISOString().substring(0, 10),
    to: value.to === undefined ? undefined : value.to.toISOString().substring(0, 10),
    cnt: value.cnt,
    growth_rate: value.growthRate,
  }
}
