/* tslint:disable */
/* eslint-disable */
/**
 * Portal DWH Service API
 * Service that provides data from DWH to the Portal
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnalyticsRelaysDaily
 */
export interface AnalyticsRelaysDaily {
    /**
     * 
     * @type {Date}
     * @memberof AnalyticsRelaysDaily
     */
    from?: Date;
    /**
     * 
     * @type {Date}
     * @memberof AnalyticsRelaysDaily
     */
    to?: Date;
    /**
     * 
     * @type {string}
     * @memberof AnalyticsRelaysDaily
     */
    categoryValue?: string;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsRelaysDaily
     */
    rateSuccess?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsRelaysDaily
     */
    rateError?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsRelaysDaily
     */
    countTotal?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsRelaysDaily
     */
    avgLatency?: number;
}

/**
 * Check if a given object implements the AnalyticsRelaysDaily interface.
 */
export function instanceOfAnalyticsRelaysDaily(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AnalyticsRelaysDailyFromJSON(json: any): AnalyticsRelaysDaily {
    return AnalyticsRelaysDailyFromJSONTyped(json, false);
}

export function AnalyticsRelaysDailyFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsRelaysDaily {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'from': !exists(json, 'from') ? undefined : (new Date(json['from'])),
        'to': !exists(json, 'to') ? undefined : (new Date(json['to'])),
        'categoryValue': !exists(json, 'category_value') ? undefined : json['category_value'],
        'rateSuccess': !exists(json, 'rate_success') ? undefined : json['rate_success'],
        'rateError': !exists(json, 'rate_error') ? undefined : json['rate_error'],
        'countTotal': !exists(json, 'count_total') ? undefined : json['count_total'],
        'avgLatency': !exists(json, 'avg_latency') ? undefined : json['avg_latency'],
    };
}

export function AnalyticsRelaysDailyToJSON(value?: AnalyticsRelaysDaily | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'from': value.from === undefined ? undefined : (value.from.toISOString().substring(0,10)),
        'to': value.to === undefined ? undefined : (value.to.toISOString().substring(0,10)),
        'category_value': value.categoryValue,
        'rate_success': value.rateSuccess,
        'rate_error': value.rateError,
        'count_total': value.countTotal,
        'avg_latency': value.avgLatency,
    };
}

