/* tslint:disable */
/* eslint-disable */
/**
 * Portal DWH Service API
 * Service that provides data from DWH to the Portal
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
import type { ResponseDataInner } from "./ResponseDataInner"
import {
  ResponseDataInnerFromJSON,
  ResponseDataInnerFromJSONTyped,
  ResponseDataInnerToJSON,
} from "./ResponseDataInner"

/**
 *
 * @export
 * @interface Response
 */
export interface Response {
  /**
   *
   * @type {Array<ResponseDataInner>}
   * @memberof Response
   */
  data?: Array<ResponseDataInner>
}

/**
 * Check if a given object implements the Response interface.
 */
export function instanceOfResponse(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function ResponseFromJSON(json: any): Response {
  return ResponseFromJSONTyped(json, false)
}

export function ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Response {
  if (json === undefined || json === null) {
    return json
  }
  return {
    data: !exists(json, "data")
      ? undefined
      : (json["data"] as Array<any>).map(ResponseDataInnerFromJSON),
  }
}

export function ResponseToJSON(value?: Response | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    data:
      value.data === undefined
        ? undefined
        : (value.data as Array<any>).map(ResponseDataInnerToJSON),
  }
}
