import NotificationsWeeklyBandwidthUsageCard from "./NotificationsWeeklyBandwidthUsageCard"
export * from "./NotificationsWeeklyBandwidthUsageCard"
export default NotificationsWeeklyBandwidthUsageCard
