import { Blockchain } from "~/models/portal/sdk"

export const CHAIN_DOCS_URL: { [key: string]: string } = {
  "arbitrum-one": "arbitrum-one-api/intro",
  "avax-mainnet": "avalanche-api/intro",
  "avax-archival": "avalanche-api/intro",
  "base-mainnet": "base-api/intro",
  "base-testnet": "base-api/intro",
  "boba-mainnet": "boba-api/intro",
  "bsc-mainnet": "binance-smart-chain-api/intro",
  "bsc-archival": "binance-smart-chain-api/intro",
  "celo-mainnet": "celo-api/intro",
  "avax-dfk": "avalanche-api/intro",
  "dogechain-mainnet": "dogechain-api/intro",
  "eth-mainnet": "ethereum-api/intro",
  "eth-archival": "ethereum-api/intro",
  "eth-trace": "ethereum-api/intro",
  "holesky-fullnode-testnet": "ethereum-api/intro",
  rinkeby: "ethereum-api/intro",
  "eth-goerli": "ethereum-api/intro",
  "goerli-archival": "ethereum-api/intro",
  "evmos-mainnet": "evmos-api/intro",
  "fantom-mainnet": "fantom-api/intro",
  "fuse-mainnet": "fuse-api/intro",
  "harmony-0": "harmony-shard-0-api/intro",
  "gnosischain-mainnet": "gnosis",
  "gnosischain-archival": "gnosis",
  "iotex-mainnet": "iotex-api/intro",
  "kava-mainnet": "kava-api/intro",
  "kava-mainnet-archival": "kava-api/intro",
  "klaytn-mainnet": "klaytn-api/intro",
  "metis-mainnet": "metis-api/intro",
  "moonbeam-mainnet": "moonbeam-api/intro",
  "moonriver-mainnet": "moonriver-api/intro",
  "near-mainnet": "near-api/intro",
  "oKc-mainnet": "okc-api/intro",
  "oasys-mainnet": "oasys-api/intro",
  "oasys-mainnet-archival": "oasys-api/intro",
  "optimism-mainnet": "optimism-api/intro",
  "optimism-archival": "optimism-api/intro",
  "osmosis-mainnet": "osmosis-api/intro",
  mainnet: "",
  "poly-mainnet": "polygon-api/intro",
  "poly-archival": "polygon-api/intro",
  "polygon-zkevm-mainnet": "polygon-api/intro",
  "polygon-mumbai": "polygon-api/intro",
  "radix-mainnet": "radix-api/intro",
  "solana-mainnet": "solana-api/intro",
  "solana-custom": "solana-api/intro",
  "sui-mainnet": "sui-api/intro",
  "scroll-mainnet": "scroll-api/intro",
  "scroll-testnet": "scroll-api/intro",
}

export const getAppEndpointUrl = (
  chain: Blockchain | undefined | null,
  appId: string | undefined,
) => `https://${chain?.blockchain}.rpc.grove.city/v1/${appId}`
