import { Blockchain } from "~/models/portal/sdk"

export const CHAIN_DOCS_URL: { [key: string]: string } = {
  "arbitrum-one": "arbitrum-one",
  "avax-mainnet": "avax",
  "avax-archival": "avax",
  "base-mainnet": "base",
  "base-testnet": "base",
  "boba-mainnet": "boba",
  "bsc-mainnet": "binance-smart-chain",
  "bsc-archival": "binance-smart-chain",
  "celo-mainnet": "celo",
  "avax-dfk": "dfk-chain-subnet",
  "dogechain-mainnet": "dogechain",
  "eth-mainnet": "ethereum",
  "eth-archival": "ethereum",
  "eth-trace": "ethereum",
  "evmos-mainnet": "evmos",
  "fantom-mainnet": "fantom",
  "fuse-mainnet": "fuse",
  "fuse-archival": "fuse",
  "gnosischain-mainnet": "gnosis",
  "gnosischain-archival": "gnosis",
  "harmony-0": "harmony-shard-0",
  "iotex-mainnet": "IoTeX",
  "kava-mainnet": "kava",
  "klaytn-mainnet": "klaytn",
  "meter-mainnet": "meter",
  "metis-mainnet": "Metis",
  "moonbeam-mainnet": "moonbeam",
  "moonriver-mainnet": "moonriver",
  "near-mainnet": "near",
  "oKc-mainnet": "okc-chain",
  "oasys-mainnet": "oasys",
  "oasys-mainnet-archival": "oasys",
  "optimism-mainnet": "optimism",
  "osmosis-mainnet": "osmosis",
  mainnet: "",
  "poly-mainnet": "polygon",
  "poly-archival": "polygon",
  "polygon-zkevm-mainnet": "polygon",
  "solana-mainnet": "solana",
  "starknet-mainnet": "starknet",
  "sui-mainnet": "sui",
  "eth-goerli": "ethereum",
  "goerli-archival": "ethereum",
  rinkeby: "ethereum",
  "polygon-mumbai": "polygon",
  "scroll-mainnet": "scroll",
  "scroll-testnet": "scroll",
  "starknet-testnet": "starknet",
}

export const getAppEndpointUrl = (
  chain: Blockchain | undefined | null,
  appId: string | undefined,
) => `https://${chain?.blockchain}.rpc.grove.city/v1/${appId}`
