import {
  Account,
  Blockchain,
  NotificationType,
  PayPlanType,
  PortalApp,
  PortalAppEnvironment,
  RoleName,
  User,
} from "./sdk"

// const testEmail = "test@test.test"
export const testPortalUserId = "userId_test"

// @ts-ignore
export const app: PortalApp = {
  id: "c7ec4cdcb4e28a19972da585",
  name: "Test Application",
  accountID: "2886d942",
  settings: {
    // @ts-ignore
    environment: "production",
    secretKey: "secretKey",
    secretKeyRequired: false,
    favoritedBlockchainIDs: null,
    monthlyRelayLimit: 0,
  },
  // @ts-ignore
  whitelists: {},
  aat: {
    a4bad02a5c85e04d843fbde4: {
      id: "id",
      publicKey: "publicKey",
      address: "address",
      clientPublicKey: "clientPublicKey",
      signature: "signature",
      version: "0.0.1",
    },
  },
  notifications: {
    // @ts-ignore
    email: {
      type: "email",
      active: true,
      destination: "",
      trigger: "",
      events: {
        full: true,
        signedUp: true,
        threeQuarters: true,
      },
    },
  },
  createdAt: "2023-04-26T16:31:21.823638Z",
  updatedAt: "2023-04-26T16:31:21.823638Z",
  deleted: false,
  firstDateSurpassed: "0001-01-01T00:00:00Z",
  legacyFields: {
    // @ts-ignore
    planType: "FREETIER_V0",
    dailyLimit: 250000,
    customLimit: 0,
    requestTimeout: 2000,
  },
}

export const blockchains: Omit<Blockchain, "scheme">[] = [
  {
    id: "0002",
    ticker: "BTC",
    description: "Bitcoin",
    blockchain: "btc-mainnet",
    active: false,
    enforceResult: "",
    chainIDCheck: "",
    logLimitBlocks: 0,
    path: "",
    blockchainAliases: ["btc-mainnet"],
  },
  {
    id: "0027",
    ticker: "GNO",
    description: "Gnosis Chain Mainnet",
    blockchain: "poa-xdai",
    active: false,
    enforceResult: "",
    chainIDCheck: '{\\"method\\":\\"eth_chainId\\",\\"id\\":1,\\"jsonrpc\\":\\"2.0\\"}',
    logLimitBlocks: 100000000,
    path: "",
    blockchainAliases: ["poa-xdai", "gnosischain-mainnet"],
  },
  {
    id: "0004",
    ticker: "BSC",
    description: "Binance Smart Chain",
    blockchain: "bsc-mainnet",
    active: false,
    enforceResult: "",
    chainIDCheck: '{\\"method\\":\\"eth_chainId\\",\\"id\\":1,\\"jsonrpc\\":\\"2.0\\"}',
    logLimitBlocks: 100000,
    path: "",
    blockchainAliases: ["bsc-mainnet"],
  },
  {
    id: "0021",
    ticker: "ETH",
    description: "Ethereum Mainnet",
    blockchain: "eth-mainnet",
    active: false,
    enforceResult: "",
    chainIDCheck: '{\\"method\\":\\"eth_chainId\\",\\"id\\":1,\\"jsonrpc\\":\\"2.0\\"}',
    logLimitBlocks: 100000,
    path: "",
    blockchainAliases: ["eth-mainnet"],
  },
  {
    id: "0022",
    ticker: "ETH",
    description: "Ethereum Mainnet Archival",
    blockchain: "eth-archival",
    active: false,
    enforceResult: "",
    chainIDCheck: '{\\"method\\":\\"eth_chainId\\",\\"id\\":1,\\"jsonrpc\\":\\"2.0\\"}',
    logLimitBlocks: 500000,
    path: "",
    blockchainAliases: ["eth-archival"],
  },
  {
    id: "0044",
    ticker: "IOT",
    description: "IoTeX Mainnet",
    blockchain: "iotex-mainnet",
    active: false,
    enforceResult: "",
    chainIDCheck: "",
    logLimitBlocks: 100000,
    path: "",
    blockchainAliases: ["iotex-mainnet"],
  },
  {
    id: "0025",
    ticker: "ETH",
    description: "Rinkeby",
    blockchain: "eth-rinkeby",
    active: false,
    enforceResult: "",
    chainIDCheck: '{\\"method\\":\\"eth_chainId\\",\\"id\\":1,\\"jsonrpc\\":\\"2.0\\"}',
    logLimitBlocks: 100000,
    path: "",
    blockchainAliases: ["eth-rinkeby"],
  },
  {
    id: "0009",
    ticker: "POLY",
    description: "Polygon Matic",
    blockchain: "poly-mainnet",
    active: false,
    enforceResult: "",
    chainIDCheck: '{\\"method\\":\\"eth_chainId\\",\\"id\\":1,\\"jsonrpc\\":\\"2.0\\"}',
    logLimitBlocks: 100000,
    path: "",
    blockchainAliases: ["poly-mainnet", "poly-rpc"],
  },
  {
    id: "0001",
    ticker: "POKT",
    description: "Pocket Network Mainnet",
    blockchain: "mainnet",
    active: false,
    enforceResult: "",
    chainIDCheck: "",
    logLimitBlocks: 0,
    path: "/v1/query/height",
    blockchainAliases: ["mainnet"],
  },
  {
    id: "000B",
    ticker: "POLY",
    description: "Polygon Matic Archival",
    blockchain: "poly-archival",
    active: false,
    enforceResult: "",
    chainIDCheck: '{\\"method\\":\\"eth_chainId\\",\\"id\\":1,\\"jsonrpc\\":\\"2.0\\"}',
    logLimitBlocks: 100000,
    path: "",
    blockchainAliases: ["poly-archival"],
  },
  {
    id: "0046",
    ticker: "EVM",
    description: "Evmos Mainnet",
    blockchain: "evmos-mainnet",
    active: false,
    enforceResult: "",
    chainIDCheck: "",
    logLimitBlocks: 100000,
    path: "",
    blockchainAliases: ["evmos-mainnet"],
  },
  {
    id: "0040",
    ticker: "HMY",
    description: "Harmony Shard 0",
    blockchain: "harmony-0",
    active: false,
    enforceResult: "",
    chainIDCheck: '{\\"method\\":\\"hmy_chainId\\",\\"id\\":1,\\"jsonrpc\\":\\"2.0\\"}',
    logLimitBlocks: 0,
    path: "",
    blockchainAliases: ["harmony-0"],
  },
  {
    id: "0010",
    ticker: "BSC",
    description: "Binance Smart Chain (Archival)",
    blockchain: "bsc-archival",
    active: false,
    enforceResult: "",
    chainIDCheck: '{\\"method\\":\\"eth_chainId\\",\\"id\\":1,\\"jsonrpc\\":\\"2.0\\"}',
    logLimitBlocks: 100000,
    path: "",
    blockchainAliases: ["bsc-archival"],
  },
  {
    id: "00A3",
    ticker: "AVAX",
    description: "AVAX Archival",
    blockchain: "avax-archival",
    active: false,
    enforceResult: "",
    chainIDCheck: "",
    logLimitBlocks: 1000000,
    path: "/ext/bc/C/rpc",
    blockchainAliases: ["avax-archival"],
  },
  {
    id: "0003",
    ticker: "AVAX",
    description: "AVAX",
    blockchain: "avax-mainnet",
    active: false,
    enforceResult: "",
    chainIDCheck: "",
    logLimitBlocks: 100000,
    path: "/ext/bc/C/rpc",
    blockchainAliases: ["avax-mainnet"],
  },
  {
    id: "0029",
    ticker: "Algo",
    description: "Algorand Mainnet",
    blockchain: "algo-mainnet",
    active: false,
    enforceResult: "",
    chainIDCheck: "",
    logLimitBlocks: 1000000,
    path: "",
    blockchainAliases: ["algo-mainnet"],
  },
  {
    id: "0024",
    ticker: "POA",
    description: "Kovan",
    blockchain: "poa-kovan",
    active: false,
    enforceResult: "",
    chainIDCheck: '{\\"method\\":\\"eth_chainId\\",\\"id\\":1,\\"jsonrpc\\":\\"2.0\\"}',
    logLimitBlocks: 100000,
    path: "",
    blockchainAliases: ["poa-kovan", "eth-kovan"],
  },
  {
    id: "000A",
    ticker: "FUSE",
    description: "Fuse Archival",
    blockchain: "fuse-archival",
    active: false,
    enforceResult: "",
    chainIDCheck: '{\\"method\\":\\"eth_chainId\\",\\"id\\":1,\\"jsonrpc\\":\\"2.0\\"}',
    logLimitBlocks: 100000,
    path: "",
    blockchainAliases: ["fuse-archival"],
  },
  {
    id: "0026",
    ticker: "ETH",
    description: "Goerli",
    blockchain: "eth-goerli",
    active: false,
    enforceResult: "",
    chainIDCheck: '{\\"method\\":\\"eth_chainId\\",\\"id\\":1,\\"jsonrpc\\":\\"2.0\\"}',
    logLimitBlocks: 100000,
    path: "",
    blockchainAliases: ["eth-goerli"],
  },
  {
    id: "000D",
    ticker: "Algo",
    description: "Algorand Archival",
    blockchain: "algo-archival",
    active: false,
    enforceResult: "",
    chainIDCheck: "",
    logLimitBlocks: 1000000,
    path: "",
    blockchainAliases: ["algo-archival"],
  },
  {
    id: "0006",
    ticker: "SOL",
    description: "Solana",
    blockchain: "solana-mainnet",
    active: false,
    enforceResult: "",
    chainIDCheck: "",
    logLimitBlocks: 0,
    path: "",
    blockchainAliases: ["solana-mainnet"],
  },
  {
    id: "000C",
    ticker: "POA",
    description: "Gnosis Chain Archival",
    blockchain: "poa-xdai-archival",
    active: false,
    enforceResult: "",
    chainIDCheck: '{\\"method\\":\\"eth_chainId\\",\\"id\\":1,\\"jsonrpc\\":\\"2.0\\"}',
    logLimitBlocks: 500000,
    path: "",
    blockchainAliases: ["poa-xdai-archival", "gnosischain-archival"],
  },
  {
    id: "0028",
    ticker: "ETH",
    description: "Ethereum Mainnet Archival with trace calls",
    blockchain: "eth-trace",
    active: false,
    enforceResult: "",
    chainIDCheck: '{\\"method\\":\\"eth_chainId\\",\\"id\\":1,\\"jsonrpc\\":\\"2.0\\"}',
    logLimitBlocks: 100000,
    path: "",
    blockchainAliases: ["eth-trace"],
  },
  {
    id: "0023",
    ticker: "ETH",
    description: "Ropsten",
    blockchain: "eth-ropsten",
    active: false,
    enforceResult: "",
    chainIDCheck: '{\\"method\\":\\"eth_chainId\\",\\"id\\":1,\\"jsonrpc\\":\\"2.0\\"}',
    logLimitBlocks: 100000,
    path: "",
    blockchainAliases: ["eth-ropsten"],
  },
  {
    id: "0047",
    ticker: "OKC",
    description: "OKC Mainnet",
    blockchain: "oKc-mainnet",
    active: false,
    enforceResult: "",
    chainIDCheck: "",
    logLimitBlocks: 100000,
    path: "",
    blockchainAliases: ["okc-mainnet", "oec-mainnet"],
  },
  {
    id: "0048",
    ticker: "BOBA",
    description: "BOBA Mainnet",
    blockchain: "boba-mainnet",
    active: false,
    enforceResult: "",
    chainIDCheck: "",
    logLimitBlocks: 100000,
    path: "",
    blockchainAliases: ["boba-mainnet"],
  },
  {
    id: "03DF",
    ticker: "AVAX_DFK",
    description: "AVAX_DFK",
    blockchain: "avax-dfk",
    active: false,
    enforceResult: "",
    chainIDCheck: "",
    logLimitBlocks: 100000,
    path: "/ext/bc/q2aTwKuyzgs8pynF7UXBZCU7DejbZbZ6EUyHr3JQzYgwNPUPi/rpc",
    blockchainAliases: ["avax-dfk"],
  },
  {
    id: "0049",
    ticker: "FTM",
    description: "Fantom Mainnet",
    blockchain: "fantom-mainnet",
    active: false,
    enforceResult: "",
    chainIDCheck: "",
    logLimitBlocks: 100000,
    path: "",
    blockchainAliases: ["fantom-mainnet"],
  },
  {
    id: "03CB",
    ticker: "CRA",
    description: "AVAX_CRA",
    blockchain: "avax-cra",
    active: false,
    enforceResult: "",
    chainIDCheck: "",
    logLimitBlocks: 100000,
    path: "/ext/bc/2K33xS9AyP9oCDiHYKVrHe7F54h2La5D8erpTChaAhdzeSu2RX/rpc",
    blockchainAliases: ["avax-cra"],
  },
  {
    id: "0052",
    ticker: "NEAR",
    description: "NEAR Mainnet",
    blockchain: "near-mainnet",
    active: false,
    enforceResult: "",
    chainIDCheck: "",
    logLimitBlocks: 100000,
    path: "",
    blockchainAliases: ["near-mainnet"],
  },
  {
    id: "0050",
    ticker: "GLMR",
    description: "Moonbeam Mainnet",
    blockchain: "moonbeam-mainnet",
    active: false,
    enforceResult: "",
    chainIDCheck: "",
    logLimitBlocks: 100000,
    path: "",
    blockchainAliases: ["moonbeam-mainnet"],
  },
  {
    id: "0051",
    ticker: "MOVR",
    description: "Moonriver Mainnet",
    blockchain: "moonriver-mainnet",
    active: false,
    enforceResult: "",
    chainIDCheck: "",
    logLimitBlocks: 100000,
    path: "",
    blockchainAliases: ["moonriver-mainnet"],
  },
  {
    id: "0005",
    ticker: "FUSE",
    description: "Fuse",
    blockchain: "fuse-mainnet",
    active: false,
    enforceResult: "",
    chainIDCheck: '{\\"method\\":\\"eth_chainId\\",\\"id\\":1,\\"jsonrpc\\":\\"2.0\\"}',
    logLimitBlocks: 100000,
    path: "",
    blockchainAliases: ["fuse-mainnet"],
  },
  {
    id: "0053",
    ticker: "OP",
    description: "Optimism Mainnet",
    blockchain: "optimism-mainnet",
    active: false,
    enforceResult: "",
    chainIDCheck: "",
    logLimitBlocks: 100000,
    path: "",
    blockchainAliases: ["optimism-mainnet"],
  },
  {
    id: "0054",
    ticker: "OSMO",
    description: "Osmosis Mainnet",
    blockchain: "osmosis-mainnet",
    active: false,
    enforceResult: "",
    chainIDCheck: "",
    logLimitBlocks: 100000,
    path: "",
    blockchainAliases: ["osmosis-mainnet"],
  },
]

export const teamsMockData = [
  {
    id: 0,
    app: "AppA",
    accepted: true,
    roleName: "ADMIN",
  },
  {
    id: 1,
    app: "AppB",
    accepted: true,
    roleName: "MEMBER",
  },
  {
    id: 2,
    app: "AppC",
    accepted: false,
    roleName: "MEMBER",
  },
  {
    id: 3,
    app: "AppD",
    accepted: false,
    roleName: "ADMIN",
  },
  {
    id: 4,
    app: "AppE",
    accepted: false,
    roleName: "ADMIN",
  },
] as const

export const profileMockData: User & { auth0ID: string } = {
  auth0ID: "auth0|230rf40fgj0jf30e",
  portalUserID: "123456",
  email: "user@pokt.network",
  iconURL: "",
  signedUp: false,
  updatesProduct: false,
  updatesMarketing: false,
  betaTester: false,
}

export const accountMockData: Account = {
  id: "08cbd8b8",
  name: "Staging",
  planType: PayPlanType.FreetierV0,
  enterpriseLimit: 0,
  monthlyUserLimit: 0,
  notifications: [
    {
      notificationType: NotificationType.Email,
      notificationSettings: {
        accountID: "",
        type: NotificationType.Email,
        active: true,
        destination: "",
        trigger: "",
        events: {
          full: true,
          half: false,
          quarter: false,
          signedUp: false,
          threeQuarters: true,
        },
      },
    },
  ],
  users: [
    {
      id: "667ba247",
      email: "rabee+3@grove.city",
      roleName: RoleName.Admin,
      accepted: true,
    },
    {
      id: "200bb0c2",
      email: "rabee+1@grove.city",
      roleName: RoleName.Member,
      accepted: false,
    },
    {
      id: "3c003c04",
      email: "rabee@grove.city",
      roleName: RoleName.Owner,
      accepted: true,
    },
  ],
  partnerChainIDs: [],
  partnerThroughputLimit: 0,
  partnerAppLimit: 0,
  integrations: {
    stripeSubscriptionID: "",
    covalentAPIKeyFree: "",
    covalentAPIKeyPaid: "",
  },
  createdAt: "2023-10-03 23:25:34.375933 +0000 UTC",
  updatedAt: "2023-11-07 15:28:49.225929 +0000 UTC",
  deleted: false,
  portalApps: [
    {
      id: "4118f1ae",
      name: "Prod",
      accountID: "08cbd8b8",
      appEmoji: "1f30d",
      description: "",
      settings: {
        appID: "",
        environment: PortalAppEnvironment.Production,
        secretKey: "3e917fa4dfa108d5c2ccc6e16df7fdc3",
        secretKeyRequired: false,
        favoritedChainIDs: [],
      },
      whitelists: {
        origins: [],
        userAgents: [],
        blockchains: [],
        contracts: [],
        methods: [],
      },
      aats: [
        {
          protocolAppID: "39fa1bea",
          aat: {
            id: "39fa1bea",
            appID: "",
            publicKey: "639b63fadbf4f77d796e74f4e599548c310f056abc7dee80f4624e60c8c4bbf9",
            address: "34d33b5b6fdcb173806a82c95de989424c15c65d",
            clientPublicKey:
              "5ad3c2acb46626b1c5e1283e26a966177b7c6f1e04a63e0350567529b42187c5",
            signature:
              "62636b7a9d91c80e27fe3b93825ffb88fd172fe813463ea5a3975749076d8b7f0c10c1b8dda4ca24475378e0b096baaa53f891a2109ec1f01010eab41f888302",
            version: "0.0.1",
          },
        },
      ],
      createdAt: "2023-10-03 23:30:34.163453 +0000 UTC",
      updatedAt: "2023-10-03 23:30:34.163453 +0000 UTC",
      deleted: false,
    },
    {
      id: "7329bb69",
      name: "Staging",
      accountID: "08cbd8b8",
      appEmoji: "1f31f",
      description: "",
      settings: {
        appID: "",
        environment: PortalAppEnvironment.Production,
        secretKey: "54d0e42cb88dfc0b653e62b0afb7f15d",
        secretKeyRequired: false,
        favoritedChainIDs: [],
      },
      whitelists: {
        origins: [],
        userAgents: [],
        blockchains: [],
        contracts: [],
        methods: [],
      },
      aats: [
        {
          protocolAppID: "144876aa",
          aat: {
            id: "144876aa",
            appID: "",
            publicKey: "3acc92f18434c01f7c4dc6e4ff27e9217b0eacbbb5f5ebcb31b4877ab19bf0c4",
            address: "531015144295e4751cdd45d3b1119befc5cfdaf9",
            clientPublicKey:
              "5ad3c2acb46626b1c5e1283e26a966177b7c6f1e04a63e0350567529b42187c5",
            signature:
              "0fbca69e3a230dfcf323200a147b3dd1a32fcae0be20b3ac5b6496bd3e4d7d31f90b2abf3d14257077230d8ffdfe29963a4ac27b634d710c42baa9b48f51f603",
            version: "0.0.1",
          },
        },
      ],
      createdAt: "2023-10-03 23:29:01.849386 +0000 UTC",
      updatedAt: "2023-10-03 23:29:01.849386 +0000 UTC",
      deleted: false,
    },
  ],
  plan: {
    id: "",
    type: PayPlanType.FreetierV0,
    monthlyRelayLimit: 0,
    chainIDs: [],
    throughputLimit: 30,
    appLimit: 0,
    dailyLimit: 100000,
  },
}
