/* tslint:disable */
/* eslint-disable */
/**
 * Portal DWH Service API
 * Service that provides data from DWH to the Portal
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

/**
 * 
 */
export class SystemApi extends runtime.BaseAPI {

    /**
     * Check the health of the service.
     */
    async healthcheckGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Portal-DWH-Service-Api-Key"] = this.configuration.apiKey("Portal-DWH-Service-Api-Key"); // apiKey authentication
        }

        const response = await this.request({
            path: `/healthcheck`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Check the health of the service.
     */
    async healthcheckGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.healthcheckGetRaw(initOverrides);
    }

}
