/* tslint:disable */
/* eslint-disable */
/**
 * Portal DWH Service API
 * Service that provides data from DWH to the Portal
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Response,
} from '../models/index';
import {
    ResponseFromJSON,
    ResponseToJSON,
} from '../models/index';

export interface AnalyticsRelaysCategoryGetRequest {
    from: Date;
    to: Date;
    category: AnalyticsRelaysCategoryGetCategoryEnum;
    accountId: Array<string>;
    portalApplicationId?: Array<string>;
    chainId?: Array<string>;
    chainMethod?: Array<string>;
}

/**
 * 
 */
export class UserApi extends runtime.BaseAPI {

    /**
     * Relays analytics retrieve aggregated values of a chosen metric category between selected dates.
     */
    async analyticsRelaysCategoryGetRaw(requestParameters: AnalyticsRelaysCategoryGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Response>> {
        if (requestParameters.from === null || requestParameters.from === undefined) {
            throw new runtime.RequiredError('from','Required parameter requestParameters.from was null or undefined when calling analyticsRelaysCategoryGet.');
        }

        if (requestParameters.to === null || requestParameters.to === undefined) {
            throw new runtime.RequiredError('to','Required parameter requestParameters.to was null or undefined when calling analyticsRelaysCategoryGet.');
        }

        if (requestParameters.category === null || requestParameters.category === undefined) {
            throw new runtime.RequiredError('category','Required parameter requestParameters.category was null or undefined when calling analyticsRelaysCategoryGet.');
        }

        if (requestParameters.accountId === null || requestParameters.accountId === undefined) {
            throw new runtime.RequiredError('accountId','Required parameter requestParameters.accountId was null or undefined when calling analyticsRelaysCategoryGet.');
        }

        const queryParameters: any = {};

        if (requestParameters.from !== undefined) {
            queryParameters['from'] = (requestParameters.from as any).toISOString().substring(0,10);
        }

        if (requestParameters.to !== undefined) {
            queryParameters['to'] = (requestParameters.to as any).toISOString().substring(0,10);
        }

        if (requestParameters.accountId) {
            queryParameters['account_id'] = requestParameters.accountId;
        }

        if (requestParameters.portalApplicationId) {
            queryParameters['portal_application_id'] = requestParameters.portalApplicationId;
        }

        if (requestParameters.chainId) {
            queryParameters['chain_id'] = requestParameters.chainId;
        }

        if (requestParameters.chainMethod) {
            queryParameters['chain_method'] = requestParameters.chainMethod;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Portal-DWH-Service-Api-Key"] = this.configuration.apiKey("Portal-DWH-Service-Api-Key"); // apiKey authentication
        }

        const response = await this.request({
            path: `/analytics/relays/{category}`.replace(`{${"category"}}`, encodeURIComponent(String(requestParameters.category))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseFromJSON(jsonValue));
    }

    /**
     * Relays analytics retrieve aggregated values of a chosen metric category between selected dates.
     */
    async analyticsRelaysCategoryGet(requestParameters: AnalyticsRelaysCategoryGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Response> {
        const response = await this.analyticsRelaysCategoryGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const AnalyticsRelaysCategoryGetCategoryEnum = {
    Transactions: 'transactions',
    Errors: 'errors'
} as const;
export type AnalyticsRelaysCategoryGetCategoryEnum = typeof AnalyticsRelaysCategoryGetCategoryEnum[keyof typeof AnalyticsRelaysCategoryGetCategoryEnum];
